import { Redis } from "@upstash/redis";

const redisUrl = process.env.UPSTASH_REDIS_REST_URL || process.env.KV_REST_API_URL;
const redisToken = process.env.UPSTASH_REDIS_REST_TOKEN || process.env.KV_REST_API_TOKEN;
const redis = redisUrl && redisToken ? new Redis({ url: redisUrl, token: redisToken }) : null;
const types = ["grazer", "coward", "hunter", "opportunist", "chaotic", "elite"] as const;
const phaseTypes = [...types, "player"] as const;
const allowed = new Set(["easy", "normal", "hard", "extreme"]);
const key = (difficulty: string) => `hinses-battlefield-2:balance:v1:${difficulty}`;
const number = (value: unknown, max: number) => Math.max(0, Math.min(max, Number(value) || 0));
const cleanCounts = (value: any, max: number) => Object.fromEntries(Object.entries(value && typeof value === "object" ? value : {}).slice(0, 30).map(([name,count]) => [String(name).replace(/[^a-z0-9 _-]/gi, "").slice(0, 30), number(count,max)]));

export default async function handler(req: any, res: any) {
  res.setHeader("Access-Control-Allow-Origin","*"); res.setHeader("Access-Control-Allow-Headers","Content-Type"); res.setHeader("Access-Control-Allow-Methods","GET,POST,OPTIONS");
  if (req.method === "OPTIONS") return res.status(204).end();
  if (!redis) return res.status(200).json({ configured: false });
  if (req.method === "GET") res.setHeader("Cache-Control", "no-store, max-age=0");
  const difficulty = String(req.method === "GET" ? req.query?.difficulty || "all" : req.body?.difficulty || "");
  if (req.method === "GET" && difficulty === "all") { const entries = await Promise.all([...allowed].map(async level => ({ difficulty:level, balance:(await redis.get<any>(key(level))) || null }))); return res.status(200).json({ configured:true, generatedAt:new Date().toISOString(), difficulties:entries }); }
  if (!allowed.has(difficulty)) return res.status(400).json({ error: "Unknown difficulty" });
  if (req.method === "GET") {
    const current = await redis.get<any>(key(difficulty));
    return res.status(200).json({ configured:true, difficulty, balance:current || null });
  }
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });
  const runId=String(req.body?.runId || "").replace(/[^a-z0-9-]/gi,"").slice(0,64); if (runId) { const fresh=await redis.sadd("hinses-battlefield-2:balance:run-ids:v1",runId); await redis.expire("hinses-battlefield-2:balance:run-ids:v1",31536000); if (!fresh) return res.status(200).json({ configured:true, duplicate:true }); }
  const current = (await redis.get<any>(key(difficulty))) || { rounds:0, abandoned:0, samples:0, wins:0, elapsed:0, playerMass:0, pressureRounds:0, bossesDefeated:0, poisonDamage:0, toxicBoltsFired:0, toxicBoltsHitPlayer:0, chaosDamage:0, chaosAiDamage:0, chaosDetonations:0, maxCombo:0, absorbed:0, duelRounds:0, duelSeconds:0, duelRivalMass:0, duelRivalPeakMax:0, duelBonus:0, peakMass:{}, top3:{}, top10Composition:{}, playerDefeats:{}, deathCauses:{}, abilityUses:{}, respawns:{}, bossAiDefeats:{}, bossCoreReturns:{}, phaseSnapshots:{}, recentRounds:[] };
  const abandoned=req.body?.status === "abandoned"; current.samples=(current.samples || current.rounds || 0)+1; current.abandoned=(current.abandoned || 0)+(abandoned ? 1 : 0); if (!abandoned) { const duelSeconds=number(req.body?.duelSeconds,900), duelRivalPeak=number(req.body?.duelRivalPeak,200000), duelBonus=number(req.body?.duelBonus,3000); current.rounds++; current.wins += req.body?.victory === true ? 1 : 0; current.elapsed += number(req.body?.elapsed, 900); current.playerMass += number(req.body?.playerMass, 200000); current.pressureRounds += req.body?.pressureReached === true ? 1 : 0; current.bossesDefeated = (current.bossesDefeated || 0) + number(req.body?.bossesDefeated, 30); current.poisonDamage = (current.poisonDamage || 0) + number(req.body?.poisonDamage, 200000); current.toxicBoltsFired = (current.toxicBoltsFired || 0) + number(req.body?.toxicBoltsFired, 10000); current.toxicBoltsHitPlayer = (current.toxicBoltsHitPlayer || 0) + number(req.body?.toxicBoltsHitPlayer, 10000); current.chaosDamage = (current.chaosDamage || 0) + number(req.body?.chaosDamage, 200000); current.chaosAiDamage = (current.chaosAiDamage || 0) + number(req.body?.chaosAiDamage, 1000000); current.chaosDetonations = (current.chaosDetonations || 0) + number(req.body?.chaosDetonations, 1000); current.maxCombo = (current.maxCombo || 0) + number(req.body?.maxCombo, 100); current.absorbed = (current.absorbed || 0) + number(req.body?.absorbed, 1000); if (duelSeconds > 0) { current.duelRounds=(current.duelRounds || 0)+1; current.duelSeconds=(current.duelSeconds || 0)+duelSeconds; current.duelRivalMass=(current.duelRivalMass || 0)+duelRivalPeak; current.duelRivalPeakMax=Math.max(current.duelRivalPeakMax || 0,duelRivalPeak); current.duelBonus=(current.duelBonus || 0)+duelBonus; } }
  current.abilityUses ||= {}; current.respawns ||= {}; current.bossAiDefeats ||= {}; current.bossCoreReturns ||= {}; for (const [name,count] of Object.entries(cleanCounts(req.body?.abilities,10000))) current.abilityUses[name]=(current.abilityUses[name]||0)+count; for (const [name,count] of Object.entries(cleanCounts(req.body?.respawns,10000))) current.respawns[name]=(current.respawns[name]||0)+count; for (const [name,count] of Object.entries(cleanCounts(req.body?.bossAiDefeats,100))) current.bossAiDefeats[name]=(current.bossAiDefeats[name]||0)+count; for (const [name,count] of Object.entries(cleanCounts(req.body?.bossCoreReturns,100))) current.bossCoreReturns[name]=(current.bossCoreReturns[name]||0)+count;
  for (const type of types) { current.peakMass[type] = (current.peakMass[type] || 0) + number(req.body?.peaks?.[type], 200000); current.top3[type] = (current.top3[type] || 0) + number(req.body?.top3?.[type], 3); current.playerDefeats[type] = (current.playerDefeats[type] || 0) + number(req.body?.defeats?.[type], 300); }
  const deathCause = String(req.body?.deathCause || "Unknown").replace(/[^a-z0-9 _-]/gi, "").slice(0, 40) || "Unknown";
  current.deathCauses[deathCause] = (current.deathCauses[deathCause] || 0) + 1;
  for (const phase of ["1:00", "2:00", "3:00", "4:00", "6:00", "end"]) { const snapshot = req.body?.phases?.[phase]; if (!snapshot || typeof snapshot !== "object") continue; current.phaseSnapshots[phase] ||= {}; for (const type of phaseTypes) { const source = snapshot[type]; if (!source || typeof source !== "object") continue; const target = current.phaseSnapshots[phase][type] ||= { count:0, mass:0, maxMass:0, averageMass:0, samples:0 }; target.count += number(source.count, 1000); target.mass += number(source.mass, 200000); target.maxMass = Math.max(target.maxMass || 0, number(source.maxMass, 200000)); target.averageMass = (target.averageMass || 0) + number(source.averageMass, 200000); target.samples += 1; } }
  const top10 = Array.isArray(req.body?.top10) ? req.body.top10.slice(0, 10).map((entry: any) => ({ type:String(entry?.type || "unknown").replace(/[^a-z]/gi, "").slice(0, 16), name:String(entry?.name || entry?.type || "unknown").replace(/[^a-z0-9 _-]/gi, "").slice(0, 24), mass:number(entry?.mass, 200000), boss:entry?.boss === true })) : [];
  current.top10Composition ||= {}; for (const entry of top10) current.top10Composition[entry.type]=(current.top10Composition[entry.type]||0)+1;
  const doctrine=["interceptor","assimilator","aegis"].includes(String(req.body?.doctrine)) ? String(req.body.doctrine) : "unknown";
  const recent = { schemaVersion:6, runId, status:abandoned ? "abandoned" : "completed", at:new Date().toISOString(), doctrine, arenaCode:String(req.body?.arenaCode || "").replace(/[^A-Z0-9-]/gi, "").slice(0, 24), victory:req.body?.victory === true, elapsed:number(req.body?.elapsed, 900), playerMass:number(req.body?.playerMass, 200000), playerRank:number(req.body?.playerRank, 1000), targetMass:number(req.body?.targetMass, 200000), score:number(req.body?.score, 1000000), absorbed:number(req.body?.absorbed, 1000), maxCombo:number(req.body?.maxCombo, 100), bossesDefeated:number(req.body?.bossesDefeated, 30), defeatedBosses:Array.isArray(req.body?.defeatedBosses) ? req.body.defeatedBosses.slice(0,12).map((name:unknown)=>String(name).replace(/[^a-z0-9 _-]/gi, "").slice(0,30)) : [], bossAiDefeats:cleanCounts(req.body?.bossAiDefeats,100), bossCoreReturns:cleanCounts(req.body?.bossCoreReturns,100), poisonDamage:number(req.body?.poisonDamage, 200000), toxicBoltsFired:number(req.body?.toxicBoltsFired,10000), toxicBoltsHitPlayer:number(req.body?.toxicBoltsHitPlayer,10000), chaosDamage:number(req.body?.chaosDamage, 200000), chaosAiDamage:number(req.body?.chaosAiDamage, 1000000), chaosDetonations:number(req.body?.chaosDetonations, 1000), duelSeconds:number(req.body?.duelSeconds,900), duelRivalPeak:number(req.body?.duelRivalPeak,200000), duelRivalName:String(req.body?.duelRivalName || "").replace(/[^a-z0-9 _-]/gi, "").slice(0,30), duelBonus:number(req.body?.duelBonus,3000), deathCause, defeats:cleanCounts(req.body?.defeats,300), peaks:cleanCounts(req.body?.peaks,200000), abilities:cleanCounts(req.body?.abilities,10000), respawns:cleanCounts(req.body?.respawns,10000), phases:req.body?.phases || {}, top10 };
  current.recentRounds = [recent, ...(Array.isArray(current.recentRounds) ? current.recentRounds : [])].slice(0, 100);
  await redis.set(key(difficulty), current);
  return res.status(200).json({ configured: true });
}
